name: CMake Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        # Include specific compiler pairings for each OS
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    #install Qt
    #this program uses new syntaxes which breaks Qt versions < 6.3.0
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.3.0'

    #vulkan
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1'
      with:
        vulkan-query-version: latest
        vulkan-components: 'Vulkan-Headers, Vulkan-Loader'
        vulkan-use-cache: true
  
    #unix dependencies
    - name: Install Dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libmpv-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew update
          brew install mpv
        fi
      shell: bash

    #windows
    - name: Install libmpv via vcpkg
      if: runner.os == 'Windows'
      run: vcpkg install mpv


    - name: Configure CMake
      # Using -B for build directory and -S for source
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        ${{ runner.os == 'Windows' && '-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake' || '' }}
        -S ${{ github.workspace }}

    - name: Build
      # --config is required for multi-config generators like MSVC on Windows
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config ${{ matrix.build_type }}
